# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               Librarian Project
tagline:             'Cool Stuff'
description:         'Project Repository'
url:                 https://jgrich.github.io/proj
baseurl:             '/proj'
paginate:            5
default_logo:        sitelogo.jpg

# About/contact
author:
  name:              Joanne Rich
  url:               https://guides.lib.uw.edu/hsl/rich
  email:             jrich@uw.edu

# Custom vars
version:             1.0.0
